---
- src: git+https://gitlab.com/osci/ansible-role-selinux.git
  name: selinux
- src: git+https://gitlab.com/osci/ansible-role-openssh.git
  name: openssh
- src: git+https://gitlab.com/osci/ansible-role-entropy.git
  name: entropy
- src: git+https://gitlab.com/osci/ansible-role-guest_virt_tools.git
  name: guest_virt_tools
- src: git+https://gitlab.com/osci/ansible-role-postfix.git
  name: postfix
- src: git+https://gitlab.com/osci/ansible-role-postgrey.git
  name: postgrey
- src: git+https://gitlab.com/osci/ansible-role-spamassassin.git
  name: spamassassin
- src: git+https://gitlab.com/osci/ansible-role-unattended_updates.git
  name: unattended_updates
- src: git+https://gitlab.com/osci/ansible-role-ah-httpd.git
  name: httpd
- src: git+https://gitlab.com/osci/ansible-role-chrony.git
  name: chrony
- src: git+https://gitlab.com/osci/ansible-role-data_movebind.git
  name: data_movebind
- src: git+https://gitlab.com/osci/ansible-role-swap_file.git
  name: swap_file
- src: git+https://gitlab.com/osci/ansible-role-lvm_partition.git
  name: lvm_partition

