---

- name: Load settings based on distribution
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "sys_{{ ansible_distribution }}.yml"
    - "sys_{{ ansible_os_family }}.yml"

- name: Disable fingerprint auth
  ansible.builtin.command: "authconfig --disablefingerprint --update"
  changed_when: True
  when: (ansible_distribution == 'Fedora' and ansible_distribution_major_version|int < 28) or (ansible_os_family == 'RedHat' and ansible_distribution_major_version|int < 7)

- name: Manage DNS Settings
  block:
    - name: Tell NM to not care about DNS Settings
      # noqa risky-file-permissions
      community.general.ini_file:
        path: /etc/NetworkManager/NetworkManager.conf
        section: main
        option: dns
        value: none
      register: nm_config
    - name: Restart NM
      ansible.builtin.service:
        name: NetworkManager
        state: restarted
      when: nm_config.changed
    - name: Configure DNS Resolution
      ansible.builtin.template:
        src: resolv.conf
        dest: /etc/resolv.conf
        owner: root
        group: root
        mode: "0644"
  when:
    - playbook_test_mode is not defined
    - ansible_os_family == 'RedHat'
  tags: dns

# do not merge with next item, since epel need to be installed first
- name: Install Epel
  ansible.builtin.package:
    pkg: epel-release
    state: present
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version|int >= 7

# cannot use 'yum copr' as yum-plugin-copr is missing on CentOS despite Copr's doc
# also there is no Ansible module for it
- name: Setup the OSAS Infra repo
  ansible.builtin.yum_repository:
    name: osas_infra
    description: Copr repo for OSAS ComInfra Team
    baseurl: "https://copr-be.cloud.fedoraproject.org/results/duck/osas-infra-team-rpm-repo/{{ rpm_repo_component }}/"
    gpgkey: "https://copr-be.cloud.fedoraproject.org/results/duck/osas-infra-team-rpm-repo/pubkey.gpg"
    repo_gpgcheck: False
    gpgcheck: True
    skip_if_unavailable: True
    state: present
    enabled: True
  when: ansible_os_family == 'RedHat'
  notify: Clean YUM Metadata

# allow for testing on selected machines
- name: Setup the OSAS Infra devel repo
  ansible.builtin.yum_repository:
    name: osas_infra_devel
    description: Copr repo for OSAS ComInfra Team
    baseurl: "https://copr-be.cloud.fedoraproject.org/results/duck/osas-infra-team-rpm-repo-devel/{{ rpm_repo_component }}/"
    gpgkey: "https://copr-be.cloud.fedoraproject.org/results/duck/osas-infra-team-rpm-repo-devel/pubkey.gpg"
    repo_gpgcheck: False
    gpgcheck: True
    skip_if_unavailable: True
    state: present
    enabled: False
  when: ansible_os_family == 'RedHat'
  notify: Clean YUM Metadata


- name: "Enable CRB RPM Repository (EL9+)"
  # noqa risky-file-permissions
  community.general.ini_file:
    path: /etc/yum.repos.d/centos.repo
    section: crb
    option: enabled
    value: '1'
    create: no
  when: ansible_distribution_major_version|int >= 9 and ansible_distribution == 'CentOS'

# after all repos are setup and before installing packages
- name: "Flush Handlers to Update Package Cache"
  ansible.builtin.meta: flush_handlers

- name: Install base tools
  ansible.builtin.package:
    pkg: "{{ item }}"
    state: present
  with_items: "{{ base_tools }}"

# TODO: report/follow upstream when we're sure
- name: Install specific needrestart config
  ansible.builtin.template:
    src: needrestart_osas.conf
    dest: /etc/needrestart/conf.d/50_osas.conf
    owner: root
    group: root
    mode: "0644"

- name: Test if the host is an AWS instance
  ansible.builtin.stat:
    path: /etc/cloud/cloud.cfg.d
  register: cloud_init

- name: Preserve AWS instance hostname
  ansible.builtin.copy:
    dest: /etc/cloud/cloud.cfg.d/06_preserve_hostname.cfg
    src: 06_preserve_hostname.cfg
    owner: root
    group: root
    mode: "0644"
  when: cloud_init.stat.isdir is defined and cloud_init.stat.isdir

- name: "Prepare firewall"
  block:
    - name: Install firewalld if available
      ansible.builtin.package:
        pkg: firewalld
        state: present
    - name: Work around cloud image who disable firewalld
      ansible.builtin.systemd:
        name: firewalld
        masked: no
        enabled: yes   # one of 'state' or 'enabled' is compulsory
      when: ansible_distribution == 'Fedora'
    - name: Start firewalld service
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: yes
  when: ansible_distribution == 'Fedora' or (ansible_os_family == 'RedHat' and ansible_distribution_major_version|int >= 7) or ansible_os_family == 'Debian'

- name: Install Kernel Module options for firewalling
  ansible.builtin.copy:
    src: firewall_kmod.conf
    dest: /etc/modprobe.d/
    owner: root
    group: root
    mode: "0644"

